import { mkdirSync, writeFileSync } from 'fs';
import path from 'path';

/**
 * Derive a URL-safe slug from the seed text for use in filenames.
 * Strips non-alphanumeric, collapses to lowercase, max 60 chars.
 */
export function deriveSlug(seed) {
  return (seed || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'untitled';
}

/**
 * Resolve the spec output path.
 * @param {string|undefined} outputDir - Override output directory (CLI flag). Defaults to ./specs
 * @param {string} slug - Derived slug
 * @returns {string} absolute path
 */
export function specPath(outputDir, slug) {
  const dir = path.resolve(outputDir || './specs');
  return path.join(dir, `deep-interview-${slug}.md`);
}

/**
 * Resolve the transcript markdown output path.
 */
export function transcriptPath(outputDir, slug) {
  const dir = path.resolve(outputDir || './specs');
  return path.join(dir, `deep-interview-${slug}-transcript.md`);
}

/**
 * Resolve the transcript JSON output path.
 */
export function transcriptJsonPath(outputDir, slug) {
  const dir = path.resolve(outputDir || './specs');
  return path.join(dir, `deep-interview-${slug}-transcript.json`);
}

/**
 * Resolve the state directory.
 * Uses XDG-style path under HOME: ~/.agentic-readiness/state/
 */
export function stateDir() {
  const home = process.env.HOME || '/tmp';
  return path.join(home, '.agentic-readiness', 'state');
}

/**
 * Resolve the state file path for a given session.
 * @param {string} sessionId
 * @returns {string}
 */
export function stateFilePath(sessionId) {
  return path.join(stateDir(), `${sessionId}.json`);
}

/**
 * Ensure a directory exists (recursively), creating it if missing.
 * @param {string} dir
 */
export function ensureDir(dir) {
  mkdirSync(dir, { recursive: true });
}

/**
 * Write a markdown transcript of the raw Q&A to disk.
 * Also writes a JSON dump of the structured answer data.
 * @param {object} state - Full session state
 * @param {string} outputDir - Output directory
 */
export function writeTranscript(state, outputDir) {
  const dir = path.resolve(outputDir || './specs');
  ensureDir(dir);
  const slug = state.slug;

  // Markdown transcript
  const mdLines = [
    `# Interview Transcript: ${state.slug}`,
    '',
    `> Generated by AgentDash Deep Interview · ${new Date().toISOString().split('T')[0]} · ${state.track} track`,
    '',
    `**Seed:** ${state.seed}`,
    `**Rounds:** ${state.round} / ${state.maxRounds}`,
    `**Ambiguity:** ${(state.ambiguity ?? 1).toFixed(3)}`,
    `**Exit:** ${state.exitReason || 'in-progress'}`,
    '',
    '---',
    '',
    '## Q&A Rounds',
    '',
  ];

  for (const a of state.answers) {
    mdLines.push(`### Round ${a.round} — *${a.dimension || '?'}*`);
    mdLines.push('');
    mdLines.push(`**Q:** ${a.question}`);
    mdLines.push('');
    mdLines.push(`**A:** ${a.answer}`);
    mdLines.push('');
  }

  if (state.ontology && Object.keys(state.ontology).length > 0) {
    mdLines.push('---');
    mdLines.push('');
    mdLines.push('## Extracted Ontology');
    mdLines.push('');
    mdLines.push('```json');
    mdLines.push(JSON.stringify(state.ontology, null, 2));
    mdLines.push('```');
  }

  mdLines.push('');
  mdLines.push('---');
  mdLines.push(`*Transcript saved at: ${new Date().toISOString()}*`);

  writeFileSync(transcriptPath(dir, slug), mdLines.join('\n'), 'utf8');

  // JSON dump — full session data for programmatic research use
  writeFileSync(
    transcriptJsonPath(dir, slug),
    JSON.stringify(
      {
        sessionId: state.sessionId,
        slug: state.slug,
        seed: state.seed,
        track: state.track,
        depth: state.depth,
        round: state.round,
        maxRounds: state.maxRounds,
        ambiguity: state.ambiguity,
        exitReason: state.exitReason,
        dimensions: state.dimensions,
        answers: state.answers,
        ontology: state.ontology || null,
        startedAt: state.startedAt,
        finishedAt: state.finishedAt || null,
      },
      null,
      2,
    ),
    'utf8',
  );
}
