/**
 * spec.js — Spec crystalliser.
 *
 * Given the full interview state (seed, answers, dimensions, ontology),
 * calls the Claude API to generate a crystallised, executable spec.
 *
 * The spec output format follows the AgentDash assessment report templates
 * (strategy.md), adapted for standalone deep-interview output (not OMC-specific).
 */

import { computeAmbiguity, getVerdict } from './score.js';

const SPEC_MODEL = 'claude-opus-4-7';
const SPEC_MODEL_FALLBACK = 'claude-sonnet-4-6';

/**
 * System prompt for the spec crystalliser.
 */
function specSystemPrompt() {
  return `You are a Senior Strategy Consultant at AgentDash Consulting. Your job is to
produce a CRYSTALLISED EXECUTABLE SPEC from a Socratic interview transcript.

FORMAT REQUIREMENTS:
Write the spec in clean Markdown. Use headers, bullet points, and tables where appropriate.
Do NOT use markdown code fences around the output — write directly to the document.

SPEC STRUCTURE:

# Deep-Interview Spec: {slug}

> Generated by @agentdash/deep-interview · {date} · ambiguous workflow assessment

## Metadata
- Session ID: {sessionId}
- Date: {date}
- Rounds: {rounds}
- Ambiguity Score: {ambiguity} (GO / CONDITIONAL / NO-GO)
- Verdict: {verdict}
- Depth: {depth}

## Problem Statement
[One paragraph: the business problem, framed as an agentic workflow. Translate any IT-layer
 language into business-layer language with a dollar figure. Who is harmed, how, and what
 does success cost?]

## Agent Tier
[Based on interview findings, classify the agent as Tier 1–5:
- Tier 1: Q&A Bot (static FAQ + RAG over small corpus)
- Tier 2: Knowledge Agent (RAG over enterprise corpus with ACL hydration)
- Tier 3: Workflow Runner (multi-step execution with approval gates, reads + writes)
- Tier 4: Review/QA Agent (observes another system's output, judges against rules)
- Tier 5: Autonomous Research/Decision Agent (multi-day work, writes-back, spawns subagents)
If target is Tier 5 but the organisation has zero agents in production, downgrade to Tier 2 or 3.]

## Workflow Definition
- **Primary function:** [What the agent does]
- **Inputs:** [What triggers / feeds the agent]
- **Outputs:** [What the agent produces]
- **Stakeholders:** [Who uses the output, who approves]

## Systems & Integrations
[Bold-named list of systems the agent touches. For each: integration method, data quality
 signal, MCP-readiness status, ACL/permission concern.]

## Closed-Loop Architecture
[Describe the four components:
1. Outcome signal — what gets measured after every run
2. Judge — how outcome is turned into reward signal
3. Memory — how the agent remembers across sessions
4. Update mechanism — how reward feeds back]

## Success Metrics
| Metric | Current Baseline | Pilot Target | Production Target |
|--------|-----------------|--------------|-------------------|
| [name] | [value]         | [value]      | [value]           |

## Risk & Governance
[Error tolerance, escalation path, audit trail, regulatory considerations.
 What happens when the agent is wrong? Who overrides?]

## Pilot Scope
[What ships in the first 4 weeks. One sentence. Named DRI. Specific success metric.]

## Buy / Hybridize / Build
[L1 (foundation): buy — Anthropic]
[L2 (connectors): buy — MCP or native API]
[L3 (orchestration): buy or build]
[L4 (domain logic): build — describe what]
[L5 (evaluation): build — describe what]
[L6 (interface): combine]
[L7 (governance): build — audit trail, budget hard-stop]

## Open Questions
[Bullet list of what the customer must still answer before pilot kickoff]

## Implementation Backlog
- [ ] **Week 1:** [milestone + checkpoint]
- [ ] **Week 2:** [milestone + checkpoint]
- [ ] **Week 3:** [milestone + checkpoint]
- [ ] **Week 4:** working agent in production
- [ ] **Week 5:** [expansion / closed-loop wiring]
- [ ] **Week 6:** [handoff prep, runbook, dashboards]

## Ontology (Extracted Entities & Relationships)
[Table: Entity | Type | Description | Relationships]

---
*Spec generated by @agentdash/deep-interview · ambiguity = {ambiguity} · rounds = {rounds}*`;
}

/**
 * Build the user prompt for spec crystallisation.
 *
 * @param {object} state - Full interview state
 * @returns {string}
 */
function buildSpecUserPrompt(state) {
  const { seed, answers, dimensions, ontology, round, depth, slug } = state;

  const lines = [];
  lines.push(`SLUG: ${slug}`);
  lines.push(`DEPTH: ${depth} (max ${state.maxRounds} rounds)`);
  lines.push(`ROUNDS COMPLETED: ${round}`);
  lines.push('');
  lines.push(`AMBIGUITY SCORE: ${state.ambiguity?.toFixed(3) ?? '?'}`);
  lines.push('');
  lines.push('DIMENSION SCORES:');
  lines.push(`  specificity: ${(dimensions.specificity ?? 0).toFixed(2)}`);
  lines.push(`  systems:     ${(dimensions.systems ?? 0).toFixed(2)}`);
  lines.push(`  success:     ${(dimensions.success ?? 0).toFixed(2)}`);
  lines.push(`  risk:        ${(dimensions.risk ?? 0).toFixed(2)}`);
  lines.push(`  fit:         ${(dimensions.fit ?? 0).toFixed(2)}`);
  lines.push('');
  lines.push(`SEED IDEA: ${seed}`);
  lines.push('');
  lines.push('INTERVIEW TRANSCRIPT:');
  if (!answers.length) {
    lines.push('(no answers — seed only)');
  } else {
    for (const a of answers) {
      lines.push(`--- Round ${a.round} [${a.dimension || '?'}] ---`);
      lines.push(`Q: ${a.question}`);
      lines.push(`A: ${a.answer}`);
      lines.push('');
    }
  }

  if (ontology && Object.keys(ontology).length > 0) {
    lines.push('');
    lines.push('ONTOLOGY (extracted entities):');
    lines.push(JSON.stringify(ontology, null, 2));
  }

  return lines.join('\n');
}

/**
 * Fill in template placeholders in the spec output.
 *
 * @param {string} spec      - Raw spec text from the model
 * @param {object} state     - Interview state
 * @returns {string}
 */
function fillSpecTemplate(spec, state) {
  const verdict = getVerdict(state.dimensions, state.threshold ?? 0.2);
  return spec
    .replace(/\{slug\}/g, state.slug || 'untitled')
    .replace(/\{date\}/g, new Date().toISOString().split('T')[0])
    .replace(/\{sessionId\}/g, state.sessionId || '?')
    .replace(/\{rounds\}/g, String(state.round || 0))
    .replace(/\{ambiguity\}/g, (state.ambiguity ?? 1).toFixed(3))
    .replace(/\{verdict\}/g, verdict)
    .replace(/\{depth\}/g, state.depth || 'standard')
    .replace(/\{ambiguity\}/g, (state.ambiguity ?? 1).toFixed(3))
    .replace(/\{rounds\}/g, String(state.round || 0));
}

/**
 * Crystallise the interview into a full spec document.
 *
 * @param {object} state - Full interview state
 * @returns {Promise<string>} the rendered spec markdown
 */
export async function crystallise(state) {
  const Anthropic = (await import('@anthropic-ai/sdk')).default;
  const apiKey = process.env.ANTHROPIC_API_KEY || process.env.CLAUDE_API_KEY;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY (or CLAUDE_API_KEY) is not set.');
  }

  const client = new Anthropic({ apiKey });

  const system = specSystemPrompt();
  const user = buildSpecUserPrompt(state);

  let result;
  try {
    result = await client.messages.create({
      model: SPEC_MODEL,
      max_tokens: 8192,
      temperature: 0.3,
      system,
      messages: [{ role: 'user', content: user }],
    });
  } catch (err) {
    if (err?.status === 404 || err?.status === 400) {
      result = await client.messages.create({
        model: SPEC_MODEL_FALLBACK,
        max_tokens: 8192,
        temperature: 0.3,
        system,
        messages: [{ role: 'user', content: user }],
      });
    } else {
      throw err;
    }
  }

  const raw = result.content[0]?.text || '';

  // Fill template placeholders
  return fillSpecTemplate(raw, state);
}

/**
 * Extract the ontology from the full transcript.
 * Calls Claude to identify entities, relationships, and stability.
 *
 * @param {object} state
 * @returns {Promise<object>} ontology object
 */
export async function extractOntology(state) {
  const Anthropic = (await import('@anthropic-ai/sdk')).default;
  const apiKey = process.env.ANTHROPIC_API_KEY || process.env.CLAUDE_API_KEY;
  if (!apiKey) return {};

  const client = new Anthropic({ apiKey });

  const transcript = state.answers.map(a => `Q: ${a.question}\nA: ${a.answer}`).join('\n\n');

  try {
    const result = await client.messages.create({
      model: SPEC_MODEL_FALLBACK,
      max_tokens: 2048,
      temperature: 0.1,
      system: `You are an ontology extractor. From the interview transcript below, extract:
1. Named entities (agents, systems, data types, stakeholders)
2. Relationships between entities (uses, produces, triggers, approves)
3. A stability score 0.0–1.0 (how stable is this ontology — low if entities are still changing)

Return JSON: { "entities": [...], "relationships": [...], "stability": <float> }`,
      messages: [{ role: 'user', content: transcript }],
    });

    const raw = result.content[0]?.text || '';
    const cleaned = raw.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
    return JSON.parse(cleaned) || {};
  } catch {
    return {};
  }
}