/**
 * spec.js — Spec crystalliser.
 *
 * Supports two output tracks:
 *   - project: tactical project charter (specificity/systems/success/risk/fit)
 *   - company: strategic portfolio scan (strategy/readiness/portfolio/risk/fit)
 */

import { computeAmbiguity, getVerdict } from './score.js';

const SPEC_MODEL = 'claude-opus-4-7';
const SPEC_MODEL_FALLBACK = 'claude-sonnet-4-6';

/**
 * System prompt for the spec crystalliser.
 * @param {string} track - 'company' | 'project'
 */
function specSystemPrompt(track = 'project') {
  if (track === 'company') {
    return companySpecSystemPrompt();
  }
  return projectSpecSystemPrompt();
}

function projectSpecSystemPrompt() {
  return `You are a Senior Strategy Consultant at AgentDash Consulting. Your job is to
produce a CRYSTALLISED PROJECT CHARTER from a Socratic interview transcript.

IMPORTANT: If a "RESEARCH CONTEXT" section appears in the user prompt (from last30days), you MUST
incorporate that research into the spec — especially into the Problem Statement, Risk & Governance,
and Peer Benchmarks sections. Ground every claim in evidence from the research where available.

FORMAT REQUIREMENTS:
Write the spec in clean Markdown. Do NOT use markdown code fences — write directly to the document.

SPEC STRUCTURE:

# Project Charter: {slug}

> Generated by @agentdash/deep-interview · {date} · project-level assessment

## Metadata
- Session ID: {sessionId}
- Date: {date}
- Rounds: {rounds}
- Ambiguity Score: {ambiguity} (GO / CONDITIONAL / NO-GO)
- Verdict: {verdict}
- Depth: {depth}

## Problem Statement
[One paragraph: the business problem. Translate IT-layer language into business-layer with a dollar
 figure. Who is harmed, how, and what does success cost?]

## Agent Tier
[Classify as Tier 1–5. If Tier 5 with zero agents in production, downgrade to Tier 2 or 3:
- Tier 1: Q&A Bot (static FAQ + RAG)
- Tier 2: Knowledge Agent (RAG over enterprise corpus with ACL hydration)
- Tier 3: Workflow Runner (multi-step execution with approval gates)
- Tier 4: Review/QA Agent (judges another system's output)
- Tier 5: Autonomous Research/Decision Agent (multi-day work, writes-back, spawns subagents)]

## Workflow Definition
- **Primary function:** [What the agent does]
- **Inputs:** [What triggers / feeds the agent]
- **Outputs:** [What the agent produces]
- **Stakeholders:** [Who uses the output, who approves]

## Systems & Integrations
[Bold-named list of systems. For each: integration method, data quality, MCP-readiness.]

## Closed-Loop Architecture
1. Outcome signal — what gets measured after every run
2. Judge — how outcome becomes a reward signal
3. Memory — how the agent remembers across sessions
4. Update mechanism — how reward feeds back

## Success Metrics
| Metric | Current Baseline | Pilot Target | Production Target |
|--------|-----------------|-------------|-----------------|
| [name] | [value]         | [value]     | [value]        |

## Risk & Governance
[Error tolerance, escalation path, audit trail, regulatory. What happens when the agent is wrong?]

## Pilot Scope
[What ships in the first 4 weeks. Named DRI. Specific success metric.]

## Buy / Hybridize / Build (Agent Factory Layers)
Apply the Agent Factory Layers framework. Commodity layers → buy. Differentiator → build.
| Layer | Recommendation | Rationale |
|-------|---------------|-----------|
| L1 Inference | BUY | vLLM, Fireworks, Azure — commodity, no advantage building |
| L2 Agent Primitives | BUY | LangChain/LangGraph — commodity tooling |
| L3 Orchestration | BUY | Temporal or equivalent — standard infrastructure |
| L4 Protocol (MCP) | BUY | MCP is the standard — build on it, don't reinvent |
| L5 Workspace | BUILD | Your differentiation lives here — Cursor, internal tooling |
| L6 Control Plane | BUILD | Governance is your moat — audit, cost attribution, policy |
| L7 Trust & Safety | SKIP | Your model provider handles this — don't buy redundant tooling |

## Open Questions
[Bullet list of what the customer must still answer before pilot kickoff]

## Implementation Backlog
- [ ] **Week 1:** [milestone]
- [ ] **Week 2:** [milestone]
- [ ] **Week 3:** [milestone]
- [ ] **Week 4:** working agent in production
- [ ] **Week 5:** [closed-loop wiring]
- [ ] **Week 6:** [handoff prep, runbook]

---
*@agentdash/deep-interview · ambiguity = {ambiguity} · rounds = {rounds}*`;
}

function companySpecSystemPrompt() {
  return `You are a Senior Strategy Consultant at AgentDash Consulting. Your job is to
produce a CRYSTALLISED PORTFOLIO SCAN from a company-level strategic assessment interview.

IMPORTANT: If a "RESEARCH CONTEXT" section appears in the user prompt (from last30days), you MUST
incorporate that research into the spec — especially into the Executive Summary, Competitive Landscape,
Peer Case Studies, and Risk Register sections. Ground every recommendation in evidence from the
research where available. If the research contradicts an assumption from the interview, note the
discrepancy explicitly.

FORMAT REQUIREMENTS:
Write in clean Markdown. Do NOT use markdown code fences — write directly to the document.

SPEC STRUCTURE:

# AI Adoption Readiness: {slug}

> Generated by @agentdash/deep-interview · {date} · company-level strategic assessment

## Metadata
- Session ID: {sessionId}
- Date: {date}
- Rounds: {rounds}
- Ambiguity Score: {ambiguity} (GO / CONDITIONAL / NO-GO)
- Verdict: {verdict}
- Depth: {depth}

## Executive Summary
[2-3 sentence executive summary. What's the overall AI adoption readiness verdict?
 What's the top recommendation?]

## AI Adoption Maturity — Current State

**Identified Level: [Level X — Name]**

Use the Five-Level AI Adoption Maturity Model to classify where the company sits today:

| Level | Name | Evidence from Interview |
|-------|------|----------------------|
| Level 1 | Unregulated Chatbots | [quote] |
| Level 2 | Claude Code & Internal Workflows | [quote] |
| Level 3 | Open-Loop Agents | [quote] |
| Level 4 | Closed-Loop Self-Learning | [quote] |
| Level 5 | Ubiquitous Agent Workforce | [quote] |

**What this means for your business:** [2-3 sentences translating the current level into business risk, competitive exposure, or missed opportunity]

**The gap to close:** [Level X → Level Y. What needs to happen to move up?]

---

## Tier Recommendation

Based on interview findings, recommend the appropriate starting agent tier:

| Tier | Name | What It Does | Build Cost | Pilot Duration | Success Metric |
|------|------|-------------|------------|----------------|----------------|
| Tier 1 | Q&A Bot | Static FAQ + RAG | £5–15k | 2–4 weeks | Support ticket reduction |
| Tier 2 | Knowledge Agent | RAG over enterprise corpus | £15–50k | 4–8 weeks | Weekly adoption rate |
| Tier 3 | Workflow Runner | Multi-step execution with approval gates | £50–150k | 6–12 weeks | Time saved per run |
| Tier 4 | Review/QA Agent | Judges another system's output | £30–100k | 6–10 weeks | Catch rate vs. human |
| Tier 5 | Autonomous Research Agent | Multi-day work, spawns subagents | £150k+ | 12–24 weeks | Decision quality vs. baseline |

**Recommended starting tier:** [Tier X] — [plain-English rationale. If Tier 5 with zero agents in production: downgrade to Tier 2 or 3 with explicit explanation of why]

## Portfolio Scan — Named Agent Projects
[Table: Project Name | Target Tier | Priority | Pilot Scope | Key Blocker]
[What specific agent projects did the company name? How are they prioritised?]

## Layer Inflection Exposure

Assess which of the seven Agent Factory Layers the company is trying to transform. Reference: [AgentDash Research — Factory Layers](https://washington-smoky.vercel.app/factory-layers)

| Layer | Name | Status | Evidence from Interview | Recommendation |
|-------|------|--------|----------------------|----------------|
| L1 | Inference | CONFIRMED / MISSING | [quote from interview] | BUY / WAIT |
| L2 | Agent Primitives | CONFIRMED / MISSING | [quote] | BUY |
| L3 | Orchestration | CONFIRMED / MISSING | [quote] | BUY |
| L4 | Protocol (MCP) | CONFIRMED / MISSING | [quote] | BUY |
| L5 | Workspace | CONFIRMED / MISSING | [quote] | BUILD |
| L6 | Control Plane | CONFIRMED / MISSING | [quote] | BUILD |
| L7 | Trust & Safety | CONFIRMED / MISSING | [quote] | SKIP (provider-owned) |

**Skipped-layer pattern:** [Flag if the company is trying to transform L5/L6 without named L1/L2/L3/L4. This is the most common failure mode.]

## Org Readiness Breakdown
[Bold-named dimensions assessed:
- AI Fluency: [score + brief]
- Data Quality: [score + brief]
- Integration Complexity: [score + brief]
- Executive Sponsorship: [score + brief]
- Change Management Capacity: [score + brief]]

## Key Blockers Identified
[Bullet list: the top 3-5 blockers preventing successful AI adoption.
 Be specific — name the actual organizational or technical issue, not symptoms.]

## Strategic Roadmap
### Phase 1 (Weeks 1-4): Foundation
[What foundational work must happen first — L1/L2 setup, data quality, team basics]

### Phase 2 (Weeks 5-12): Pilot
[Specific pilot agent project with named scope, DRI, success metric]

### Phase 3 (Months 4-6): Scale
[What does expansion look like? How many agents, what integration points?]

## Diana Hu Operating Model Recommendations
- **DRI:** [Who owns AI adoption?]
- **Funding:** [CAPEX / OPEX / project budget?]
- **Team Size:** [Current vs. required AI team headcount]
- **Measurement:** [How does the org measure AI success today vs. target state?]

## Risk Register
[Top 3 risks to the AI adoption plan with likelihood and mitigation.]

## Recommended Next Steps
[Numbered list. What should the CTO do in the next 2 weeks?]

---
*@agentdash/deep-interview · ambiguity = {ambiguity} · rounds = {rounds}*`;
}

/**
 * Build the user prompt for spec crystallisation.
 * @param {object} state
 * @param {string} [researchContext] - Optional research from last30days
 * @returns {string}
 */
function buildSpecUserPrompt(state, researchContext) {
  const { seed, answers, dimensions, ontology, round, depth, slug, track } = state;

  const lines = [
    `TRACK: ${(track || 'project').toUpperCase()}`,
    `SLUG: ${slug}`,
    `DEPTH: ${depth} (max ${state.maxRounds} rounds)`,
    `ROUNDS COMPLETED: ${round}`,
    '',
    `AMBIGUITY SCORE: ${state.ambiguity?.toFixed(3) ?? '?'}`,
    '',
  ];

  if (track === 'company') {
    lines.push('DIMENSION SCORES:');
    lines.push(`  strategy:  ${(dimensions.strategy ?? 0).toFixed(2)}`);
    lines.push(`  readiness: ${(dimensions.readiness ?? 0).toFixed(2)}`);
    lines.push(`  portfolio: ${(dimensions.portfolio ?? 0).toFixed(2)}`);
    lines.push(`  risk:      ${(dimensions.risk ?? 0).toFixed(2)}`);
    lines.push(`  fit:       ${(dimensions.fit ?? 0).toFixed(2)}`);
  } else {
    lines.push('DIMENSION SCORES:');
    lines.push(`  specificity: ${(dimensions.specificity ?? 0).toFixed(2)}`);
    lines.push(`  systems:     ${(dimensions.systems ?? 0).toFixed(2)}`);
    lines.push(`  success:     ${(dimensions.success ?? 0).toFixed(2)}`);
    lines.push(`  risk:        ${(dimensions.risk ?? 0).toFixed(2)}`);
    lines.push(`  fit:         ${(dimensions.fit ?? 0).toFixed(2)}`);
  }

  lines.push('');
  lines.push(`SEED: ${seed}`);

  if (researchContext) {
    lines.push('');
    lines.push('--- RESEARCH CONTEXT (from last30days) ---');
    lines.push(researchContext);
    lines.push('--- END RESEARCH ---');
  }

  lines.push('');
  lines.push('INTERVIEW TRANSCRIPT:');
  if (!answers.length) {
    lines.push('(no answers — seed only)');
  } else {
    for (const a of answers) {
      lines.push(`--- Round ${a.round} [${a.dimension || '?'}] ---`);
      lines.push(`Q: ${a.question}`);
      lines.push(`A: ${a.answer}`);
      lines.push('');
    }
  }

  if (ontology && Object.keys(ontology).length > 0) {
    lines.push('');
    lines.push('ONTOLOGY (extracted entities):');
    lines.push(JSON.stringify(ontology, null, 2));
  }

  return lines.join('\n');
}

/**
 * Fill in template placeholders in the spec output.
 * @param {string} spec
 * @param {object} state
 * @returns {string}
 */
function fillSpecTemplate(spec, state) {
  const verdict = getVerdict(state.dimensions, state.threshold ?? 0.2, state.track ?? 'project');
  const DISCLAIMER = '\n\n---\n\n> **Disclaimer:** This assessment is AI-generated from user-provided interview responses and available research context. It may contain incomplete assumptions, interpretation errors, or outdated information. Review and verify all content before publishing, sharing, or making business decisions from it.\n';
  return spec
    .replace(/\{slug\}/g, state.slug || 'untitled')
    .replace(/\{date\}/g, new Date().toISOString().split('T')[0])
    .replace(/\{sessionId\}/g, state.sessionId || '?')
    .replace(/\{rounds\}/g, String(state.round || 0))
    .replace(/\{ambiguity\}/g, (state.ambiguity ?? 1).toFixed(3))
    .replace(/\{verdict\}/g, verdict)
    .replace(/\{depth\}/g, state.depth || 'standard') +
    DISCLAIMER;
}

/**
 * Find the first text block in a Claude API response content array.
 * The response may contain thinking blocks before the text block.
 */
function getTextContent(result) {
  if (!result.content) return '';
  for (const block of result.content) {
    if (block.type === 'text') return block.text || '';
  }
  return '';
}

/**
 * Crystallise the interview into a spec document.
 * @param {object} state
 * @param {string} [researchContext] - Optional research from last30days
 * @returns {Promise<string>}
 */
export async function crystallise(state, researchContext) {
  const Anthropic = (await import('@anthropic-ai/sdk')).default;
  const apiKey =
    process.env.ANTHROPIC_API_KEY ||
    process.env.CLAUDE_API_KEY ||
    process.env.ANTHROPIC_AUTH_TOKEN ||
    null;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY (or CLAUDE_API_KEY or ANTHROPIC_AUTH_TOKEN) is not set.');
  }

  const client = new Anthropic({ apiKey });
  const track = state.track || 'project';
  const system = specSystemPrompt(track);
  const user = buildSpecUserPrompt(state, researchContext);

  let result;
  try {
    result = await client.messages.create({
      model: SPEC_MODEL,
      max_tokens: 8192,
      temperature: 0.3,
      system,
      messages: [{ role: 'user', content: user }],
    });
  } catch (err) {
    if (err?.status === 404 || err?.status === 400) {
      result = await client.messages.create({
        model: SPEC_MODEL_FALLBACK,
        max_tokens: 8192,
        temperature: 0.3,
        system,
        messages: [{ role: 'user', content: user }],
      });
    } else {
      throw err;
    }
  }

  const raw = getTextContent(result);
  return fillSpecTemplate(raw, state);
}

/**
 * Extract the ontology from the full transcript.
 * @param {object} state
 * @returns {Promise<object>}
 */
export async function extractOntology(state) {
  const Anthropic = (await import('@anthropic-ai/sdk')).default;
  const apiKey =
    process.env.ANTHROPIC_API_KEY ||
    process.env.CLAUDE_API_KEY ||
    process.env.ANTHROPIC_AUTH_TOKEN ||
    null;
  if (!apiKey) return {};

  const client = new Anthropic({ apiKey });
  const transcript = state.answers.map(a => `Q: ${a.question}\nA: ${a.answer}`).join('\n\n');

  try {
    const result = await client.messages.create({
      model: SPEC_MODEL_FALLBACK,
      max_tokens: 2048,
      temperature: 0.1,
      system: `You are an ontology extractor. From the interview transcript below, extract:
1. Named entities (agents, systems, data types, stakeholders)
2. Relationships between entities (uses, produces, triggers, approves)
3. A stability score 0.0–1.0 (how stable is this ontology)

Return JSON: { "entities": [...], "relationships": [...], "stability": <float> }`,
      messages: [{ role: 'user', content: transcript }],
    });

    const raw = result.content[0]?.text || '';
    const cleaned = raw.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
    return JSON.parse(cleaned) || {};
  } catch {
    return {};
  }
}
