/**
 * spec.js — Spec crystalliser.
 *
 * Supports two output tracks:
 *   - project: tactical project charter (specificity/systems/success/risk/fit)
 *   - company: strategic portfolio scan (strategy/readiness/portfolio/risk/fit)
 */

import { computeAmbiguity, getVerdict } from './score.js';

const SPEC_MODEL = 'claude-opus-4-7';
const SPEC_MODEL_FALLBACK = 'claude-sonnet-4-6';

/**
 * System prompt for the spec crystalliser.
 * @param {string} track - 'company' | 'project'
 */
function specSystemPrompt(track = 'project') {
  if (track === 'company') {
    return companySpecSystemPrompt();
  }
  return projectSpecSystemPrompt();
}

function projectSpecSystemPrompt() {
  return `You are a Senior Strategy Consultant at AgentDash Consulting. Your job is to
produce a CRYSTALLISED PROJECT CHARTER from a Socratic interview transcript.

FORMAT REQUIREMENTS:
Write the spec in clean Markdown. Do NOT use markdown code fences — write directly to the document.

SPEC STRUCTURE:

# Project Charter: {slug}

> Generated by @agentdash/deep-interview · {date} · project-level assessment

## Metadata
- Session ID: {sessionId}
- Date: {date}
- Rounds: {rounds}
- Ambiguity Score: {ambiguity} (GO / CONDITIONAL / NO-GO)
- Verdict: {verdict}
- Depth: {depth}

## Problem Statement
[One paragraph: the business problem. Translate IT-layer language into business-layer with a dollar
 figure. Who is harmed, how, and what does success cost?]

## Agent Tier
[Classify as Tier 1–5. If Tier 5 with zero agents in production, downgrade to Tier 2 or 3:
- Tier 1: Q&A Bot (static FAQ + RAG)
- Tier 2: Knowledge Agent (RAG over enterprise corpus with ACL hydration)
- Tier 3: Workflow Runner (multi-step execution with approval gates)
- Tier 4: Review/QA Agent (judges another system's output)
- Tier 5: Autonomous Research/Decision Agent (multi-day work, writes-back, spawns subagents)]

## Workflow Definition
- **Primary function:** [What the agent does]
- **Inputs:** [What triggers / feeds the agent]
- **Outputs:** [What the agent produces]
- **Stakeholders:** [Who uses the output, who approves]

## Systems & Integrations
[Bold-named list of systems. For each: integration method, data quality, MCP-readiness.]

## Closed-Loop Architecture
1. Outcome signal — what gets measured after every run
2. Judge — how outcome becomes a reward signal
3. Memory — how the agent remembers across sessions
4. Update mechanism — how reward feeds back

## Success Metrics
| Metric | Current Baseline | Pilot Target | Production Target |
|--------|-----------------|-------------|-----------------|
| [name] | [value]         | [value]     | [value]         |

## Risk & Governance
[Error tolerance, escalation path, audit trail, regulatory. What happens when the agent is wrong?]

## Pilot Scope
[What ships in the first 4 weeks. Named DRI. Specific success metric.]

## Buy / Hybridize / Build (Seven-Layer Stack)
[L1: buy · L2: buy (MCP) · L3: buy · L4: build · L5: build · L6: combine · L7: build]

## Open Questions
[Bullet list of what the customer must still answer before pilot kickoff]

## Implementation Backlog
- [ ] **Week 1:** [milestone]
- [ ] **Week 2:** [milestone]
- [ ] **Week 3:** [milestone]
- [ ] **Week 4:** working agent in production
- [ ] **Week 5:** [closed-loop wiring]
- [ ] **Week 6:** [handoff prep, runbook]

---
*@agentdash/deep-interview · ambiguity = {ambiguity} · rounds = {rounds}*`;
}

function companySpecSystemPrompt() {
  return `You are a Senior Strategy Consultant at AgentDash Consulting. Your job is to
produce a CRYSTALLISED PORTFOLIO SCAN from a company-level strategic assessment interview.

FORMAT REQUIREMENTS:
Write in clean Markdown. Do NOT use markdown code fences — write directly to the document.

SPEC STRUCTURE:

# AI Adoption Readiness: {slug}

> Generated by @agentdash/deep-interview · {date} · company-level strategic assessment

## Metadata
- Session ID: {sessionId}
- Date: {date}
- Rounds: {rounds}
- Ambiguity Score: {ambiguity} (GO / CONDITIONAL / NO-GO)
- Verdict: {verdict}
- Depth: {depth}

## Executive Summary
[2-3 sentence executive summary. What's the overall AI adoption readiness verdict?
 What's the top recommendation?]

## AI Maturity Score (1-5)
[Score the company's overall AI adoption maturity across:
- Data infrastructure readiness
- AI/ML team capabilities
- Executive sponsorship strength
- Existing agent deployments
- Change management capacity
Provide a score 1-5 with brief justification.]

## Tier Recommendation
[Based on interview findings, recommend the appropriate starting agent tier:
- Tier 1: Q&A Bot
- Tier 2: Knowledge Agent (RAG over enterprise corpus)
- Tier 3: Workflow Runner (approval gates, reads + writes)
- Tier 4: Review/QA Agent
- Tier 5: Autonomous Research/Decision Agent
If recommending Tier 5 but zero current agents in production: downgrade to Tier 2/3 with rationale.]

## Portfolio Scan — Named Agent Projects
[Table: Project Name | Target Tier | Priority | Pilot Scope | Key Blocker]
[What specific agent projects did the company name? How are they prioritised?]

## Layer Inflection Exposure
[Assess which of the Seven Layers the company is trying to transform:
- L1: Foundation primitives (LLM API, vector DB)
- L2: Connectors (MCP servers, API wrappers)
- L3: Orchestration (agent framework, memory, tools)
- L4: Domain logic (prompts, workflows, business rules)
- L5: Evaluation (test suites, hit-rate tracking)
- L6: Interface (dashboards, notification routing)
- L7: Governance (budget hard-stops, audit trail)
Note which layers are named vs. missing. Flag skipped-layer patterns.]

## Org Readiness Breakdown
[Bold-named dimensions assessed:
- AI Fluency: [score + brief]
- Data Quality: [score + brief]
- Integration Complexity: [score + brief]
- Executive Sponsorship: [score + brief]
- Change Management Capacity: [score + brief]]

## Key Blockers Identified
[Bullet list: the top 3-5 blockers preventing successful AI adoption.
 Be specific — name the actual organizational or technical issue, not symptoms.]

## Strategic Roadmap
### Phase 1 (Weeks 1-4): Foundation
[What foundational work must happen first — L1/L2 setup, data quality, team basics]

### Phase 2 (Weeks 5-12): Pilot
[Specific pilot agent project with named scope, DRI, success metric]

### Phase 3 (Months 4-6): Scale
[What does expansion look like? How many agents, what integration points?]

## Diana Hu Operating Model Recommendations
- **DRI:** [Who owns AI adoption?]
- **Funding:** [CAPEX / OPEX / project budget?]
- **Team Size:** [Current vs. required AI team headcount]
- **Measurement:** [How does the org measure AI success today vs. target state?]

## Risk Register
[Top 3 risks to the AI adoption plan with likelihood and mitigation.]

## Recommended Next Steps
[Numbered list. What should the CTO do in the next 2 weeks?]

---
*@agentdash/deep-interview · ambiguity = {ambiguity} · rounds = {rounds}*`;
}

/**
 * Build the user prompt for spec crystallisation.
 * @param {object} state
 * @returns {string}
 */
function buildSpecUserPrompt(state) {
  const { seed, answers, dimensions, ontology, round, depth, slug, track } = state;

  const lines = [
    `TRACK: ${(track || 'project').toUpperCase()}`,
    `SLUG: ${slug}`,
    `DEPTH: ${depth} (max ${state.maxRounds} rounds)`,
    `ROUNDS COMPLETED: ${round}`,
    '',
    `AMBIGUITY SCORE: ${state.ambiguity?.toFixed(3) ?? '?'}`,
    '',
  ];

  if (track === 'company') {
    lines.push('DIMENSION SCORES:');
    lines.push(`  strategy:  ${(dimensions.strategy ?? 0).toFixed(2)}`);
    lines.push(`  readiness: ${(dimensions.readiness ?? 0).toFixed(2)}`);
    lines.push(`  portfolio: ${(dimensions.portfolio ?? 0).toFixed(2)}`);
    lines.push(`  risk:      ${(dimensions.risk ?? 0).toFixed(2)}`);
    lines.push(`  fit:       ${(dimensions.fit ?? 0).toFixed(2)}`);
  } else {
    lines.push('DIMENSION SCORES:');
    lines.push(`  specificity: ${(dimensions.specificity ?? 0).toFixed(2)}`);
    lines.push(`  systems:     ${(dimensions.systems ?? 0).toFixed(2)}`);
    lines.push(`  success:     ${(dimensions.success ?? 0).toFixed(2)}`);
    lines.push(`  risk:        ${(dimensions.risk ?? 0).toFixed(2)}`);
    lines.push(`  fit:         ${(dimensions.fit ?? 0).toFixed(2)}`);
  }

  lines.push('');
  lines.push(`SEED: ${seed}`);
  lines.push('');
  lines.push('INTERVIEW TRANSCRIPT:');
  if (!answers.length) {
    lines.push('(no answers — seed only)');
  } else {
    for (const a of answers) {
      lines.push(`--- Round ${a.round} [${a.dimension || '?'}] ---`);
      lines.push(`Q: ${a.question}`);
      lines.push(`A: ${a.answer}`);
      lines.push('');
    }
  }

  if (ontology && Object.keys(ontology).length > 0) {
    lines.push('');
    lines.push('ONTOLOGY (extracted entities):');
    lines.push(JSON.stringify(ontology, null, 2));
  }

  return lines.join('\n');
}

/**
 * Fill in template placeholders in the spec output.
 * @param {string} spec
 * @param {object} state
 * @returns {string}
 */
function fillSpecTemplate(spec, state) {
  const verdict = getVerdict(state.dimensions, state.threshold ?? 0.2, state.track ?? 'project');
  return spec
    .replace(/\{slug\}/g, state.slug || 'untitled')
    .replace(/\{date\}/g, new Date().toISOString().split('T')[0])
    .replace(/\{sessionId\}/g, state.sessionId || '?')
    .replace(/\{rounds\}/g, String(state.round || 0))
    .replace(/\{ambiguity\}/g, (state.ambiguity ?? 1).toFixed(3))
    .replace(/\{verdict\}/g, verdict)
    .replace(/\{depth\}/g, state.depth || 'standard');
}

/**
 * Crystallise the interview into a spec document.
 * @param {object} state
 * @returns {Promise<string>}
 */
export async function crystallise(state) {
  const Anthropic = (await import('@anthropic-ai/sdk')).default;
  const apiKey = process.env.ANTHROPIC_API_KEY || process.env.CLAUDE_API_KEY;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY (or CLAUDE_API_KEY) is not set.');
  }

  const client = new Anthropic({ apiKey });
  const track = state.track || 'project';
  const system = specSystemPrompt(track);
  const user = buildSpecUserPrompt(state);

  let result;
  try {
    result = await client.messages.create({
      model: SPEC_MODEL,
      max_tokens: 8192,
      temperature: 0.3,
      system,
      messages: [{ role: 'user', content: user }],
    });
  } catch (err) {
    if (err?.status === 404 || err?.status === 400) {
      result = await client.messages.create({
        model: SPEC_MODEL_FALLBACK,
        max_tokens: 8192,
        temperature: 0.3,
        system,
        messages: [{ role: 'user', content: user }],
      });
    } else {
      throw err;
    }
  }

  const raw = result.content[0]?.text || '';
  return fillSpecTemplate(raw, state);
}

/**
 * Extract the ontology from the full transcript.
 * @param {object} state
 * @returns {Promise<object>}
 */
export async function extractOntology(state) {
  const Anthropic = (await import('@anthropic-ai/sdk')).default;
  const apiKey = process.env.ANTHROPIC_API_KEY || process.env.CLAUDE_API_KEY;
  if (!apiKey) return {};

  const client = new Anthropic({ apiKey });
  const transcript = state.answers.map(a => `Q: ${a.question}\nA: ${a.answer}`).join('\n\n');

  try {
    const result = await client.messages.create({
      model: SPEC_MODEL_FALLBACK,
      max_tokens: 2048,
      temperature: 0.1,
      system: `You are an ontology extractor. From the interview transcript below, extract:
1. Named entities (agents, systems, data types, stakeholders)
2. Relationships between entities (uses, produces, triggers, approves)
3. A stability score 0.0–1.0 (how stable is this ontology)

Return JSON: { "entities": [...], "relationships": [...], "stability": <float> }`,
      messages: [{ role: 'user', content: transcript }],
    });

    const raw = result.content[0]?.text || '';
    const cleaned = raw.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
    return JSON.parse(cleaned) || {};
  } catch {
    return {};
  }
}
